### ISSUE TITLE
No work in cshtml file

### ISSUE THREAD

**Issue by DavoBR** [herrherrmann/angular-bootstrap-code#2]
Would be a good idea if it can be used in cshtml files

**Comment by herrherrmann** [comment]
Hey there, I looked into adding cshtml support.
What you could definitely do for now, is adjusting your `settings.json` to treat cshtml as html files:
```
"files.associations": {
    "*.cshtml": "html"
}
```
This might disable any other language features you're relying on for cshtml (I hope that's not the case!).

I'm not sure if I want to adjust the snippets to cover cshtml (and other html flavors) by default because there's no nice way to do this at the moment.
